# This rule is not used by the project kilo-clustermesh-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kilo.squat.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kilo-clustermesh-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: clustermesh-viewer-role
rules:
  - apiGroups:
      - kilo.squat.ai
    resources:
      - clustermeshes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kilo.squat.ai
    resources:
      - clustermeshes/status
    verbs:
      - get
