apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kilo-clustermesh-remote
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kilo.squat.ai
    resources:
      - peers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
