apiVersion: v2
name: cozy-kilo-clustermesh-operator
description: Cozystack package wrapping the Kilo ClusterMesh operator
type: application
version: 0.0.0
appVersion: "0.1.0"
dependencies:
  - name: kilo-clustermesh-operator
    version: "0.1.0"
    repository: "file://../../../charts/kilo-clustermesh-operator"
