apiVersion: kilo.squat.ai/v1alpha1
kind: ClusterMesh
metadata:
  labels:
    app.kubernetes.io/name: kilo-clustermesh-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustermesh-sample
spec:
  # TODO(user): Add fields here
