apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kilo-clustermesh-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kilo-clustermesh-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kilo-clustermesh-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kilo-clustermesh-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kilo-clustermesh-operator.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ include "kilo-clustermesh-operator.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--leader-elect={{ .Values.leaderElect }}"
            - "--metrics-bind-address={{ .Values.metricsBindAddress }}"
            - "--metrics-secure={{ .Values.metricsSecure }}"
            - "--health-probe-bind-address={{ .Values.healthProbeBindAddress }}"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
